version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: korea
      MYSQL_USER: arom
      MYSQL_PASSWORD: 1234

    volumes:
      - ./data:/var/lib/mysql

volumes:
  db_data:
