version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dockerTest
      MYSQL_USER: son
      MYSQL_PASSWORD: 1234

    volumes:
      - ./data:/var/lib/mysql

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: son
      DB_PASSWORD: 1234
      DB_NAME: dockerTest
    depends_on:
      - db

volumes:
  db_data:
